default: &default
  adapter: mysql2
  collation: utf8mb4_unicode_ci
  encoding: utf8mb4
  database: <%= ENV.fetch("MYSQL_DATABASE", "demo") %>
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", nil) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
